Document: spirv-tools
Title: Debian spirv-tools Manual
Author: <insert document author here>
Abstract: This manual describes what spirv-tools is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/spirv-tools/spirv-tools.sgml.gz

Format: postscript
Files: /usr/share/doc/spirv-tools/spirv-tools.ps.gz

Format: text
Files: /usr/share/doc/spirv-tools/spirv-tools.text.gz

Format: HTML
Index: /usr/share/doc/spirv-tools/html/index.html
Files: /usr/share/doc/spirv-tools/html/*.html
