name: build-ubuntu-packages
run-name: Build Debian style packages for Ubuntu
on:
  push:
  workflow_call:
    inputs:
      spirv_headers:
        required: false
        type: string
        default: '{"repo":"","ref":""}'
      spirv_tools:
        required: true
        type: string
        default: '{"repo":"johnzupin/SPIRV-Tools","ref":"ubuntu/focal"}'
        description: "A json object that defines repo and ref. Ex) {repo:johnzupin/SPIRV-Tools, ref:ubuntu/focal}"
  workflow_dispatch:
    inputs:
      spirv_headers:
        required: false
        type: string
        default: '{"repo":"","ref":""}'
      spirv_tools:
        required: true
        type: string
        default: '{"repo":"johnzupin/SPIRV-Tools","ref":"ubuntu/focal"}'
        description: "A json object that defines repo and ref. Ex) {repo:johnzupin/SPIRV-Tools, ref:ubuntu/focal}"
jobs:
  get-spirv-headers-ref:
    runs-on: ubuntu-latest
    outputs:
      spirv-headers-repo: ${{ steps.deps-refs.outputs.SPV_HEADERS_REPO }}
      spirv-headers-ref: ${{ steps.deps-refs.outputs.SPV_HEADERS_REF }}
      spirv-tools-repo: ${{ steps.deps-refs.outputs.SPV_TOOLS_REPO }}
      spirv-tools-ref: ${{ steps.deps-refs.outputs.SPV_TOOLS_REF }}
    steps:
      - name: "Inputs have been specified - Set repo/ref variables with specified input"
        if: ${{ inputs.spirv_tools != '' }}
        run: |
          echo SPV_HEADERS_REPO="${{ fromJSON(inputs.spirv_headers).repo }}" >> "$GITHUB_ENV"
          echo SPV_HEADERS_REF="${{ fromJSON(inputs.spirv_headers).ref }}" >> "$GITHUB_ENV"
          echo SPV_TOOLS_REPO="${{ fromJSON(inputs.spirv_tools).repo }}" >> "$GITHUB_ENV"
          echo SPV_TOOLS_REF="${{ fromJSON(inputs.spirv_tools).ref }}" >> "$GITHUB_ENV"
      - name: "No inputs specified - Checkout repository to get dependency versions from repository DEPS file" 
        if: ${{ inputs.spirv_tools == '' }}
        uses: actions/checkout@v4
      - name: "No input specified - Parse the DEPS file to get the dependency refs for building package dependencies"
        if: ${{ inputs.spirv_tools == '' }}
        run: |
          echo SPV_HEADERS_REPO="KhronosGroup/SPIRV-Headers" >> "$GITHUB_ENV"
          echo SPV_HEADERS_REF=`grep -m1 'spirv_headers_revision' DEPS | tr -d \ \', | cut -d: -f2` >> "$GITHUB_ENV"
          echo SPV_TOOLS_REPO="$GITHUB_REPOSITORY" >> "$GITHUB_ENV"
          echo SPV_TOOLS_REF="$GITHUB_REF_NAME" >> "$GITHUB_ENV"
      - id: deps-refs
        run: |
          echo SPV_HEADERS_REPO="${{ env.SPV_HEADERS_REPO }}" >> "$GITHUB_OUTPUT"
          echo SPV_HEADERS_REF="${{ env.SPV_HEADERS_REF }}" >> "$GITHUB_OUTPUT"
          echo SPV_TOOLS_REPO="${{ env.SPV_TOOLS_REPO }}" >> "$GITHUB_OUTPUT"
          echo SPV_TOOLS_REF="${{ env.SPV_TOOLS_REF }}" >> "$GITHUB_OUTPUT"

  build-spirv-tools-amd64-focal-package:
    needs: [ "get-spirv-headers-ref" ]
    runs-on: ubuntu-20.04
    steps:
      - name: "Install CMake using KitWare's repo"
        run: |
          sudo apt-get update && sudo apt-get install -y wget gpg
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
          echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | sudo tee /etc/apt/sources.list.d/kitware.list
      - name: "Update and Install build dependencies"
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y \
          wget git cmake build-essential git-buildpackage python3 debhelper
      - uses: actions/checkout@v4
        with:
          path: ${{github.workspace}}/SPIRV-Headers
          repository: "${{needs.get-spirv-headers-ref.outputs.spirv-headers-repo}}"
          ref: "${{needs.get-spirv-headers-ref.outputs.spirv-headers-ref}}"
      - name: "Build and Install SPIRV-Headers"
        run: |
          cmake -S ${{github.workspace}}/SPIRV-Headers -B ${{github.workspace}}/SPIRV-Headers -DCMAKE_BUILD_TYPE="Release"
          sudo cmake --install ${{github.workspace}}/SPIRV-Headers --prefix /usr
      - name: "Checkout SPIRV-Tools"
        uses: actions/checkout@v4
      - run: "gbp buildpackage --git-verbose --git-force-create --git-upstream-tree=branch --git-ignore-branch --git-upstream-branch=ubuntu/focal --git-component=external --no-sign --no-check-builddeps"
      - uses: actions/upload-artifact@v4
        with:
          name: "spirv-tools-focal-package"
          path: "${{ runner.workspace }}/spirv-tools*20.04*amd64.deb"
